import { QueryProvider } from "@/providers/query-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// const geistSans = Geist({
//     subsets: ["latin"],
//     display: "swap",
//     adjustFontFallback: true,
//     variable: "--font-geist-sans",
// });

// const geistMono = Geist_Mono({
//     subsets: ["latin"],
//     display: "swap",
//     adjustFontFallback: true,
//     variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Amishrit",
  description: "Generated by create next app",
  icons: {
    icon: "/Amishrit.png"
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={inter.className}
      >
        <ClerkProvider>
            <QueryProvider>
              {children}
              <Toaster />
            </QueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
