import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider";
import { Toaster } from "sonner";
import { ReduxProvider } from "@/react-redux/redux-provider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amishrit",
  description: "Generated by create next app",
  icons: {
    icon: "/Amishrit.png"
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

      <ReduxProvider>
      <QueryProvider>
        {children}
        <Toaster />
        </QueryProvider>
      </ReduxProvider>

      </body>
    </html>
    </ClerkProvider>
  );
}
